FROM node:16

WORKDIR /app

RUN npx next telemetry disable

COPY package.json package.json
COPY yarn.lock yarn.lock

RUN yarn install --ignore-scripts --ignore-optional

COPY . .

EXPOSE 3000

CMD yarn dev

