import { Box, Container, Typography } from '@mui/material';
import Head from 'next/head';

export default function About() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxWidth={'xl'}>
          <Box my={5}>
            <Typography variant="h1">About</Typography>
          </Box>
        </Container>
      </main>
    </div>
  );
}
