import { Container, Typography } from '@mui/material';
import Head from 'next/head';
import DashboardLayout from './layout';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DashboardLayout>
          <Container maxWidth={'xl'}>
            <Typography variant="h1">Dashboard</Typography>
            <Typography variant="h2"></Typography>
          </Container>

        </DashboardLayout>
      </main>
    </div>
  );
}
